# Create virtual environment with command:
#
#   $ CONDA_OVERRIDE_CUDA=11.7 conda env create --file conda-recipe.yaml
#

name: rlhf-trojan-competition
channels:
  - huggingface
  - pytorch
  - nvidia/label/cuda-11.7.1
  - defaults
  - conda-forge
dependencies:
  - python = 3.10
  - pip
  - pytorch::pytorch = 2.0.1
  - pytorch-cuda=11.7
  - transformers = 4.29.0
  - datasets
  - tokenizers >= 0.13.3
  - optree
  - scipy
  - nvitop
  - matplotlib-base
  - rich
  - tqdm
  - typing-extensions
  - sentencepiece
